name: KanjiMemory
options:
  bundleIdPrefix: com.kanjimemory
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  KanjiMemory:
    type: application
    platform: iOS
    sources:
      - path: KanjiMemory
        excludes:
          - "**/*.xcassets"
      - path: KanjiMemory/Resources/Assets.xcassets
    resources:
      - path: KanjiMemory/Resources/Data
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: KanjiMemory/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.kanjimemory.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: KanjiMemory/KanjiMemory.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default

  KanjiMemoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - KanjiMemoryTests
    dependencies:
      - target: KanjiMemory
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kanjimemory.tests

  KanjiMemoryUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - KanjiMemoryUITests
    dependencies:
      - target: KanjiMemory
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kanjimemory.uitests

schemes:
  KanjiMemory:
    build:
      targets:
        KanjiMemory: all
        KanjiMemoryTests: [test]
        KanjiMemoryUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KanjiMemoryTests
        - KanjiMemoryUITests
    archive:
      config: Release
